### ISSUE TITLE
在图片没有被编辑的情况下重新加载图片报错 mask.data为空

### ISSUE THREAD

**Issue by caochenyu** [todaylg/Magic-Matting#1]
因为在初始化Canvas的时候 mask = null;
在未编辑情况下mask.data为空
所以建议在reloadImg中添加判断
`if(mask){
        	var _ref3 = [[], mask.data];
	        mask.data = _ref3[0];
	        mask.predata = _ref3[1];
        }`

**Comment by todaylg** [comment]
谢谢反馈，已添加容错
